function [record, fs] = slmg_read_Intan_files(rootpath, window)

% read_Intan_RHD2000_file
%
% Version 2.0, 20 October 2016
%
% Reads Intan Technologies RHD2000 data file generated by evaluation board
% GUI or Intan Recording Controller.  Data are parsed and placed into
% variables that appear in the base MATLAB workspace.  Therefore, it is
% recommended to execute a 'clear' command before running this program to
% clear all other variables from the base workspace.
%
% Example:
% >> clear
% >> read_Intan_RHD2000_file
% >> whos
% >> amplifier_channels(1)
% >> plot(t_amplifier, amplifier_data(1,:))

if ~(exist(rootpath, 'file') == 7)
    fprintf('Selected record path not found (%s)', rootpath)
    return;
end

if isempty(window)
    fs=0;
    return;
end

record.data = [];
record.times = [];

d = dir(fullfile(rootpath, '*.rhd'));

numFiles = length(d);

for i=1:numFiles
    file = d(i).name;
    [amplifier_data, t_amplifier, ~, fs] = slmg_read_Intan_file(rootpath, file);
    
    
     keep = (t_amplifier>window(1)) .* (t_amplifier<window(2));
     record.data = [record.data amplifier_data(:, keep==1)];
     record.times = [record.times t_amplifier(keep==1)];
     if (t_amplifier(end)>window(2))
         break;
     end
end


end

